<?php
header('Cache-Control: no-store');
header('X-Frame-Options: DENY');
header('X-Content-Type-Options: nosniff');
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Painel | Black White Festas</title><link rel="stylesheet" href="admin.css"></head><body>
<header><a href="../index.html"><img src="../images/logo.jpg" alt="Black White Festas"></a><span>Painel administrativo</span><button id="logout" hidden>Sair</button></header>
<main><p id="message" role="status"></p>
<section id="loginPanel" class="login panel"><p class="eyebrow">BLACK WHITE FESTAS</p><h1 id="loginTitle">Acesse sua agenda</h1><p id="loginHelp">Entre para gerenciar reservas e equipamentos.</p><form id="loginForm"><label>Usuário<input name="username" autocomplete="username" required maxlength="80"></label><label>Senha<input name="password" type="password" autocomplete="current-password" required maxlength="1024"></label><button class="primary" type="submit" id="loginButton">Entrar</button></form></section>
<div id="dashboard" hidden>
<div class="heading"><div><p class="eyebrow">SUA OPERAÇÃO, EM UM SÓ LUGAR</p><h1>Agenda de festas</h1><p>Reservas pendentes e confirmadas ocupam o equipamento. Cancelamentos liberam o período.</p></div><button id="newBooking" class="primary">+ Nova reserva</button></div>
<section class="panel"><form id="settingsForm" class="toolbar"><div><h2>Intervalo entre locações</h2><p>Tempo após a retirada para desmontagem e transporte do mesmo brinquedo.</p></div><label>Margem em minutos<input id="turnaround" name="turnaroundMinutes" type="number" min="0" max="1440" required></label><button type="submit">Salvar margem</button></form></section>
<section class="panel"><div class="toolbar"><h2>Calendário por brinquedo</h2><label>Equipamento<select id="toyFilter"></select></label><button id="newMaintenance">Bloquear manutenção</button></div><div class="monthnav"><button id="prevMonth" aria-label="Mês anterior">←</button><h3 id="monthTitle"></h3><button id="nextMonth" aria-label="Próximo mês">→</button></div><div class="week"><span>Dom</span><span>Seg</span><span>Ter</span><span>Qua</span><span>Qui</span><span>Sex</span><span>Sáb</span></div><div id="calendar" class="calendar"></div><p class="legend">Verde: livre · Amarelo: pendente · Vermelho: confirmado · Cinza: manutenção</p><div id="dayDetails" aria-live="polite"></div></section>
<section class="panel"><div class="toolbar"><h2>Reservas e manutenções</h2><label>Buscar<input id="search" placeholder="Cliente, telefone ou endereço"></label><label>Situação<select id="statusFilter"><option value="">Todas</option><option value="pending">Pendentes</option><option value="confirmed">Confirmadas</option><option value="cancelled">Canceladas</option></select></label></div><div class="tablewrap"><table><thead><tr><th>Registro</th><th>Período</th><th>Brinquedos</th><th>Situação</th><th>Total</th><th>Ações</th></tr></thead><tbody id="rows"></tbody></table></div><p id="empty" hidden>Nenhum registro encontrado.</p></section>
</div>
<dialog id="editor"><form id="bookingForm"><div class="toolbar"><h2 id="editorTitle">Nova reserva</h2><button type="button" id="closeEditor" aria-label="Fechar">✕</button></div><input type="hidden" name="id" value="0"><div class="formgrid"><label>Tipo<select name="kind"><option value="rental">Reserva</option><option value="maintenance">Manutenção</option></select></label><label>Situação<select name="status"><option value="pending">Pendente</option><option value="confirmed">Confirmada</option><option value="cancelled">Cancelada</option></select></label><label class="wide">Cliente / motivo da manutenção<input name="name" required maxlength="120"></label><label>Telefone<input name="phone" type="tel" maxlength="40"></label><label>Taxa de entrega (R$)<input name="fee" type="number" min="0" max="100000" step="0.01" value="0"></label><label class="wide">Endereço<input name="address" maxlength="500"></label><label>Instalação / início<input name="start" type="datetime-local" required></label><label>Retirada / fim<input name="end" type="datetime-local" required></label><fieldset class="wide"><legend>Brinquedos</legend><div id="toyChoices"></div></fieldset><label class="wide">Observações<textarea name="notes" maxlength="2000" rows="3"></textarea></label></div><p id="editorError" role="alert"></p><button class="primary" type="submit">Salvar registro</button></form></dialog>
</main><script src="admin.js"></script></body></html>
